make 0.77 branch healthy again
Signed-off-by: Arkadiusz <arkadiusz.kasprzyk@swmansion.com>


# message auto-generated for no-merge-commit merge:
merge kas/fix-target-branch-2025-04-24 into 0.77.1-rc.1-ohos

chore: make branch healthy

Created-by: arkadiuszkasprzyk
Commit-by: Arkadiusz
Merged-by: huangyouhua
Description: ## Why is this change needed
This MR fixes the 0.77 branch. Currently, the compilation fails with this error:

```
1 ERROR: ArkTS:ERROR File: /Users/pafry/projects/test/ohos_react_native/packages/tester/harmony/react_native_openharmony/src/main/ets/RNOHCorePackage/turboModules/AlertManagerTurboModule.ts:61:57
 Property 'tertiaryButtons' does not exist on type 'AlertOptions'. Did you mean 'tertiaryButton'?
 ```
 
 Also Image.abortPrefetch test fails in concurrent tester. This test depends on time and it passes when it's run in isolation, that's why I marked it as a sequential test case.

See merge request: openharmony-sig/ohos_react_native!865